"""Fn-ptr module emitter for production JIT codegen.

Generates lightweight kernel .so modules (~5s compile) that export function
pointers consumed by the pre-compiled JIT engine .so. No training infrastructure
is imported — only GPU kernel math, memory management, and blas for materialized.

Architecture:
    codegen_engine (SymPy → IR → passes) → fn_ptr_module.py → .mojo source
    → mojo build (~5s) → kernel.so (fn ptrs)
    → engine.so (pre-compiled) calls fn ptrs for training/prediction
"""

from .gpu_kernel import (
    emit_forward_matvec,
    emit_forward_matvec_splitj,
    emit_gradient_matvec,
    emit_cross_matvec,
    emit_extract_diagonal,
    emit_fill_kernel_matrix,
    emit_fill_cross_covariance,
    emit_noise_matvec,
    emit_single_gradient_matvec,
    emit_kronecker_forward_matvec,
    emit_kronecker_gradient_matvec,
    emit_mixed_forward_matvec,
    emit_mixed_gradient_matvec,
    emit_mixed_cross_matvec,
    emit_mixed_materialize,
    emit_mixed_extract_diagonal,
)
from .mojo_printer import collect_math_imports, emit_ir
from ..ir import IRKernel
from ..schedule import ScheduleConfig


def emit_fn_ptr_module(
    kernel: IRKernel,
    schedule: ScheduleConfig,
    module_name: str = "jit_kernel",
    dim: int = 0,
) -> str:
    """Generate complete .mojo source for a fn-ptr kernel module.

    The generated module exports init_provider() and materialize() Python
    bindings. init_provider() returns a dict of function pointer addresses
    that the JIT engine .so uses to call kernel operations.

    Args:
        kernel: Optimized IRKernel from the codegen pipeline
        schedule: GPU execution schedule (TM, shmem, ncols, block_size)
        module_name: Name for the generated Python module
        dim: Input dimension (uses kernel.dim if 0)

    Returns:
        Complete .mojo source code string ready for compilation
    """
    if dim == 0:
        dim = kernel.dim
    num_params = kernel.num_params
    block_size = schedule.block_size
    ncols_list = schedule.ncols
    splitj_default = schedule.splitj_forward
    is_ard = any(str(name).rsplit("_", 1)[-1].isdigit() for name in kernel.param_names)

    parts = []

    # 1. Header + imports
    parts.append(_emit_header(kernel, dim, num_params, block_size, module_name))

    # 2. GPU kernels
    parts.append("# " + "=" * 77)
    parts.append("# GPU Kernels (auto-generated by codegen_engine)")
    parts.append("# " + "=" * 77)

    parts.append(emit_forward_matvec(kernel, schedule))
    parts.append(emit_forward_matvec_splitj(kernel, schedule))
    parts.append(emit_gradient_matvec(kernel, schedule))
    parts.append(emit_single_gradient_matvec(kernel, schedule))
    parts.append(emit_cross_matvec(kernel, schedule))
    parts.append(emit_extract_diagonal(kernel, schedule))
    parts.append(emit_fill_kernel_matrix(kernel, schedule))
    parts.append(emit_fill_cross_covariance(kernel, schedule))
    parts.append(emit_noise_matvec(kernel, schedule))
    parts.append(emit_kronecker_forward_matvec(kernel, schedule))
    parts.append(emit_kronecker_gradient_matvec(kernel, schedule))
    parts.append(emit_mixed_forward_matvec(kernel, schedule))
    parts.append(emit_mixed_gradient_matvec(kernel, schedule))
    parts.append(emit_mixed_cross_matvec(kernel, schedule))
    parts.append(emit_mixed_materialize(kernel, schedule))
    parts.append(emit_mixed_extract_diagonal(kernel, schedule))

    # 3. Provider struct
    parts.append(_emit_provider_struct(num_params))

    # 4. Fn-ptr implementations
    parts.append(
        _emit_fn_ptr_implementations(
            kernel, dim, num_params, block_size, ncols_list, schedule.tm, splitj_default
        )
    )

    # 5. Fn-ptr type aliases + Python bindings
    parts.append(_emit_helpers_and_bindings(num_params, module_name, is_ard))

    return "\n".join(parts)


# =============================================================================
# Module Sections
# =============================================================================


def _emit_header(
    kernel: IRKernel,
    dim: int,
    num_params: int,
    block_size: int,
    module_name: str,
) -> str:
    """Emit imports and aliases — minimal, no training infrastructure."""
    math_imports = collect_math_imports(kernel)

    return f'''"""JIT kernel module: {module_name}
Auto-generated by mojogp.codegen_engine (fn-ptr architecture)
DIM={dim}, NPARAMS={num_params}, BLOCK={block_size}
"""
from python import PythonObject, Python
from python.bindings import PythonModuleBuilder
from gpu.host import DeviceContext, DeviceBuffer, HostBuffer
from gpu import block_dim, block_idx, thread_idx
from gpu.sync import barrier
from gpu.memory import external_memory, AddressSpace
from memory import UnsafePointer
from memory import alloc
{math_imports}
from math import ceildiv
from collections import InlineArray
from os import abort, getenv
from buffer import NDBuffer
from layout.layout import Layout
from layout.layout_tensor import LayoutTensor
from layout.runtime_layout import RuntimeLayout
from linalg.matmul.vendor.blas import matmul as blas_matmul
from utils.index import IndexList

alias DIM = {dim}
alias NPARAMS = {num_params}
alias BLOCK = {block_size}
'''


def _emit_provider_struct(num_params: int) -> str:
    """Emit the JITProvider struct (heap-allocated, accessed via pointer)."""
    return f"""
# {"=" * 77}
# Provider struct (heap-allocated, accessed via provider_ptr)
# {"=" * 77}

struct JITProvider(Movable):
    var ctx: DeviceContext
    var params_host: UnsafePointer[Float32, MutAnyOrigin]   # [NPARAMS] on HOST
    var params_gpu_owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]
    var params_gpu: UnsafePointer[Float32, MutAnyOrigin]    # [NPARAMS] on GPU
    var noise: Float32
    var noise_mode: Int  # 0=scalar, 1=fixed vector, 2=learned vector, 3=learned grouped, 4=learned linear input-dependent
    var noise_vec_owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]
    var noise_vec_ptr: UnsafePointer[Float32, MutAnyOrigin]
    var noise_group_owner: UnsafePointer[DeviceBuffer[DType.int32], MutAnyOrigin]
    var noise_group_ptr: UnsafePointer[Int32, MutAnyOrigin]
    var num_noise_groups: Int
    var n: Int
    var dim: Int
    var x_owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]
    var x_ptr: UnsafePointer[Float32, MutAnyOrigin]    # [n * dim] on GPU
    var diagonal_val: Float32                           # K(x,x) diagonal
    var k_matrix_owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]
    var k_matrix_ptr: UnsafePointer[Float32, MutAnyOrigin]  # [n*n] on GPU (materialized)
    var is_materialized: Bool
    var materialization_mode: Int  # 0=none, 1=continuous, 2=mixed
    var materialized_corr_ptr: UnsafePointer[Float32, MutAnyOrigin]

    fn __init__(out self, ctx: DeviceContext,
                params_host: UnsafePointer[Float32, MutAnyOrigin],
                params_gpu_owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin],
                params_gpu: UnsafePointer[Float32, MutAnyOrigin],
                noise: Float32, n: Int, dim: Int,
                x_owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin],
                x_ptr: UnsafePointer[Float32, MutAnyOrigin]):
        self.ctx = ctx
        self.params_host = params_host
        self.params_gpu_owner = params_gpu_owner
        self.params_gpu = params_gpu
        self.noise = noise
        self.noise_mode = 0
        self.noise_vec_owner = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
        self.noise_vec_ptr = UnsafePointer[Float32, MutAnyOrigin]()
        self.noise_group_owner = UnsafePointer[DeviceBuffer[DType.int32], MutAnyOrigin]()
        self.noise_group_ptr = UnsafePointer[Int32, MutAnyOrigin]()
        self.num_noise_groups = 0
        self.n = n
        self.dim = dim
        self.x_owner = x_owner
        self.x_ptr = x_ptr
        self.diagonal_val = Float32(1.0)
        self.k_matrix_owner = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
        self.k_matrix_ptr = UnsafePointer[Float32, MutAnyOrigin]()
        self.is_materialized = False
        self.materialization_mode = 0
        self.materialized_corr_ptr = UnsafePointer[Float32, MutAnyOrigin]()
"""


def _emit_fn_ptr_implementations(
    kernel: IRKernel,
    dim: int,
    num_params: int,
    block_size: int,
    ncols_list: list,
    tm: int,
    splitj_default: bool,
) -> str:
    """Emit all fn-ptr implementation functions."""
    bs = block_size
    forward_tm = max(int(tm), 1)
    splitj_default_literal = "True" if splitj_default else "False"

    code = f"""
# {"=" * 77}
# Function pointer implementations (called from engine .so)
# {"=" * 77}

fn _get_prov(addr: Int) -> UnsafePointer[JITProvider, MutAnyOrigin]:
    var slot = alloc[Int](1)
    slot[] = addr
    var result = slot.bitcast[UnsafePointer[JITProvider, MutAnyOrigin]]()[]
    slot.free()
    return result

fn _free_device_buffer_owner(
    owner: UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]
):
    if Int(owner) != 0:
        owner.destroy_pointee()
        owner.free()

fn _free_int32_device_buffer_owner(
    owner: UnsafePointer[DeviceBuffer[DType.int32], MutAnyOrigin]
):
    if Int(owner) != 0:
        owner.destroy_pointee()
        owner.free()

fn _destroy_provider_owned_buffers(
    prov: UnsafePointer[JITProvider, MutAnyOrigin]
):
    _free_device_buffer_owner(prov[].params_gpu_owner)
    _free_device_buffer_owner(prov[].x_owner)
    _free_device_buffer_owner(prov[].k_matrix_owner)
    _free_device_buffer_owner(prov[].noise_vec_owner)
    _free_int32_device_buffer_owner(prov[].noise_group_owner)
    if Int(prov[].params_host) != 0:
        prov[].params_host.free()
    prov[].params_gpu_owner = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
    prov[].params_gpu = UnsafePointer[Float32, MutAnyOrigin]()
    prov[].noise_mode = 0
    prov[].noise_vec_owner = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
    prov[].noise_vec_ptr = UnsafePointer[Float32, MutAnyOrigin]()
    prov[].noise_group_owner = UnsafePointer[DeviceBuffer[DType.int32], MutAnyOrigin]()
    prov[].noise_group_ptr = UnsafePointer[Int32, MutAnyOrigin]()
    prov[].num_noise_groups = 0
    prov[].x_owner = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
    prov[].x_ptr = UnsafePointer[Float32, MutAnyOrigin]()
    prov[].k_matrix_owner = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
    prov[].k_matrix_ptr = UnsafePointer[Float32, MutAnyOrigin]()
    prov[].params_host = UnsafePointer[Float32, MutAnyOrigin]()
    prov[].is_materialized = False
    prov[].materialization_mode = 0
    prov[].materialized_corr_ptr = UnsafePointer[Float32, MutAnyOrigin]()

fn _destroy_provider(prov: UnsafePointer[JITProvider, MutAnyOrigin]):
    _destroy_provider_owned_buffers(prov)
    prov.destroy_pointee()
    prov.free()

fn _use_vendor_dense_matmul() -> Bool:
    return getenv("MOJOGP_USE_MAX_MATMUL", "1") != "0"

fn _use_2d_materialized_fill() -> Bool:
    return getenv("MOJOGP_USE_2D_MATERIALIZED_FILL", "0") != "0"

fn _use_splitj_forward(n: Int) -> Bool:
    var override = getenv("MOJOGP_USE_SPLITJ_FORWARD", "")
    if override != "":
        return override != "0"
    return {splitj_default_literal} and n >= 2000

fn _provider_scalar_noise(prov: UnsafePointer[JITProvider, MutAnyOrigin]) -> Float32:
    if prov[].noise_mode == 0:
        return prov[].noise
    return Float32(0.0)

fn _add_provider_noise(
    ctx: DeviceContext,
    prov: UnsafePointer[JITProvider, MutAnyOrigin],
    out_ptr: UnsafePointer[Float32, MutAnyOrigin],
    v_ptr: UnsafePointer[Float32, MutAnyOrigin],
    total: Int,
) raises:
    var grid_noise = ceildiv(total, BLOCK)
    if prov[].noise_mode == 0:
        ctx.enqueue_function[kernel_add_noise_vec](
            out_ptr, v_ptr, total, prov[].noise,
            grid_dim=grid_noise, block_dim=BLOCK)
    elif prov[].noise_mode == 1 or prov[].noise_mode == 2 or prov[].noise_mode == 3 or prov[].noise_mode == 4:
        ctx.enqueue_function[kernel_add_noise_vector_vec](
            out_ptr, v_ptr, prov[].noise_vec_ptr, total, prov[].n,
            grid_dim=grid_noise, block_dim=BLOCK)

fn _add_provider_vector_noise_if_needed(
    ctx: DeviceContext,
    prov: UnsafePointer[JITProvider, MutAnyOrigin],
    out_ptr: UnsafePointer[Float32, MutAnyOrigin],
    v_ptr: UnsafePointer[Float32, MutAnyOrigin],
    total: Int,
) raises:
    if prov[].noise_mode == 1 or prov[].noise_mode == 2 or prov[].noise_mode == 3 or prov[].noise_mode == 4:
        ctx.enqueue_function[kernel_add_noise_vector_vec](
            out_ptr, v_ptr, prov[].noise_vec_ptr, total, prov[].n,
            grid_dim=ceildiv(total, BLOCK), block_dim=BLOCK)

fn _kernel_gemm_matvec_naive(
    out_ptr: UnsafePointer[Float32, MutAnyOrigin],
    K_ptr: UnsafePointer[Float32, MutAnyOrigin],
    v_ptr: UnsafePointer[Float32, MutAnyOrigin],
    n: Int,
    num_cols: Int,
) -> None:
    var i = block_idx.x * block_dim.x + thread_idx.x
    var col = block_idx.y * block_dim.y + thread_idx.y
    if i >= UInt(n) or col >= UInt(num_cols):
        return
    var sum_val = Float32(0.0)
    for j in range(n):
        sum_val += K_ptr[UInt(i) * UInt(n) + UInt(j)] * v_ptr[UInt(col) * UInt(n) + UInt(j)]
    out_ptr[UInt(col) * UInt(n) + UInt(i)] = sum_val

fn _dense_matvec_naive(
    ctx: DeviceContext,
    out_ptr: UnsafePointer[Float32, MutAnyOrigin],
    K_ptr: UnsafePointer[Float32, MutAnyOrigin],
    v_ptr: UnsafePointer[Float32, MutAnyOrigin],
    n: Int,
    num_cols: Int,
) raises:
    alias BX = 16
    alias BY = 16
    ctx.enqueue_function[_kernel_gemm_matvec_naive](
        out_ptr, K_ptr, v_ptr, n, num_cols,
        grid_dim=((n + BX - 1) // BX, (num_cols + BY - 1) // BY),
        block_dim=(BX, BY),
    )

fn _do_materialize(prov: UnsafePointer[JITProvider, MutAnyOrigin]) raises:
    \"\"\"Compute K matrix on GPU and store in provider.\"\"\"
    var ctx = prov[].ctx
    var n = prov[].n
    if not prov[].is_materialized:
        var K_buf = ctx.enqueue_create_buffer[DType.float32](n * n)
        prov[].k_matrix_ptr = K_buf.unsafe_ptr()
        var K_heap = alloc[DeviceBuffer[DType.float32]](1)
        K_heap.init_pointee_move(K_buf^)
        prov[].k_matrix_owner = K_heap
        prov[].is_materialized = True
    prov[].materialization_mode = 1
    prov[].materialized_corr_ptr = UnsafePointer[Float32, MutAnyOrigin]()
    if _use_2d_materialized_fill():
        alias TILE = 16
        ctx.enqueue_function[fused_fill_kernel_matrix_2d[DIM]](
            prov[].k_matrix_ptr, prov[].x_ptr, prov[].params_gpu, n,
            grid_dim=(ceildiv(n, TILE), ceildiv(n, TILE)), block_dim=(TILE, TILE))
    else:
        var grid = ceildiv(n, BLOCK)
        ctx.enqueue_function[fused_fill_kernel_matrix[DIM]](
            prov[].k_matrix_ptr, prov[].x_ptr, prov[].params_gpu, n,
            grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    # --- impl_forward_matvec ---
    code += f"""
fn impl_forward_matvec(provider_ptr: Int,
                       out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                       v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                       num_cols: Int) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var noise = _provider_scalar_noise(prov)

    if prov[].is_materialized:
        # Match the AOT materialized provider's runtime BLAS toggle so
        # fair-lane experiments can actually switch the JIT dense path too.
        if _use_vendor_dense_matmul():
            alias KStaticLayout = Layout.row_major[2]()
            alias VStaticLayout = Layout.col_major[2](IndexList[2](-1, -1))
            alias OutStaticLayout = Layout.col_major[2](IndexList[2](-1, -1))
            var k_runtime = RuntimeLayout[KStaticLayout].row_major(IndexList[2](n, n))
            var v_runtime = RuntimeLayout[VStaticLayout].col_major(IndexList[2](n, num_cols))
            var out_runtime = RuntimeLayout[OutStaticLayout].col_major(IndexList[2](n, num_cols))
            var K_tensor = LayoutTensor[DType.float32, KStaticLayout](prov[].k_matrix_ptr, k_runtime)
            var V_tensor = LayoutTensor[DType.float32, VStaticLayout](v_ptr, v_runtime)
            var out_tensor = LayoutTensor[DType.float32, OutStaticLayout](out_ptr, out_runtime)
            blas_matmul[use_tf32=False](
                ctx, out_tensor, K_tensor, V_tensor,
                c_row_major=False, transpose_a=False, transpose_b=False
            )
        else:
            _dense_matvec_naive(ctx, out_ptr, prov[].k_matrix_ptr, v_ptr, n, num_cols)
        _add_provider_noise(ctx, prov, out_ptr, v_ptr, n * num_cols)
        ctx.synchronize()
        return

    var x = prov[].x_ptr
    var p = prov[].params_gpu
    var grid = ceildiv(n, BLOCK * {forward_tm})

    if _use_splitj_forward(n):
        alias MAX_SPLITJ_CHUNKS = 8
        var num_chunks = MAX_SPLITJ_CHUNKS
        if n < BLOCK * MAX_SPLITJ_CHUNKS:
            num_chunks = ceildiv(n, BLOCK)
        var chunk_size = ceildiv(n, num_chunks)
        var partial_buf = ctx.enqueue_create_buffer[DType.float32](num_chunks * n * num_cols)
        var partial_ptr = partial_buf.unsafe_ptr()
"""

    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc) * 4
        code += f"        {cond} num_cols == {nc}:\n"
        code += (
            f"            ctx.enqueue_function[fused_forward_matvec_splitj_partials[DIM, {nc}]](\n"
        )
        code += f"                partial_ptr, x, v_ptr, p, n, chunk_size,\n"
        code += (
            f"                grid_dim=(grid, num_chunks), block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )
        code += (
            f"            ctx.enqueue_function[reduce_splitj_forward_ncols[{nc}]](\n"
        )
        code += f"                out_ptr, partial_ptr, v_ptr, n, num_chunks, noise,\n"
        code += f"                grid_dim=(ceildiv(n, BLOCK), {nc}), block_dim=BLOCK)\n"
        code += "            _add_provider_vector_noise_if_needed(ctx, prov, out_ptr, v_ptr, n * num_cols)\n"
        code += "            ctx.synchronize()\n"
        code += "            _ = partial_buf\n"
        code += "            return\n"

    code += "        _ = partial_buf\n"

    # NCOLS dispatch for forward
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc) * 4
        code += f"    {cond} num_cols == {nc}:\n"
        code += (
            f"        ctx.enqueue_function[fused_forward_matvec_ncols[DIM, {nc}]](\n"
        )
        code += f"            out_ptr, x, v_ptr, p, n, noise,\n"
        code += (
            f"            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )

    code += """    else:
        var col_start = 0
        while col_start < num_cols:
"""
    for nc in sorted(ncols_list, reverse=True):
        shmem = bs * (dim + nc) * 4
        code += f"""            if num_cols - col_start >= {nc}:
                var v_chunk = v_ptr.offset(col_start * n)
                var out_chunk = out_ptr.offset(col_start * n)
                ctx.enqueue_function[fused_forward_matvec_ncols[DIM, {nc}]](
                    out_chunk, x, v_chunk, p, n, noise,
                    grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})
                col_start += {nc}
                continue
"""
    code += """    _add_provider_vector_noise_if_needed(ctx, prov, out_ptr, v_ptr, n * num_cols)
    ctx.synchronize()
"""

    # --- impl_gradient_matvec (single param) ---
    code += f"""
fn impl_gradient_matvec(provider_ptr: Int,
                        out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                        v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                        num_cols: Int, param_index: Int, sync: Bool) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
    ctx.enqueue_function[single_gradient_matvec[DIM]](
        out_ptr, prov[].x_ptr, v_ptr, prov[].params_gpu, n, num_cols, param_index,
        grid_dim=grid, block_dim=BLOCK)
    if sync:
        ctx.synchronize()
"""

    # --- impl_fused_gradient_matvec ---
    code += f"""
fn impl_fused_gradient_matvec(provider_ptr: Int,
                              out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              num_cols: Int) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
"""

    # NCOLS dispatch for fused gradient
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc) * 4
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_all_gradients_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, prov[].x_ptr, v_ptr, prov[].params_gpu, n,\n"
        code += (
            f"            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )

    code += f"""    else:
        # Fallback: per-param gradient
        for pi in range(NPARAMS):
            var grad_out = out_ptr.offset(pi * n * num_cols)
            ctx.enqueue_function[single_gradient_matvec[DIM]](
                grad_out, prov[].x_ptr, v_ptr, prov[].params_gpu, n, num_cols, pi,
                grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    # --- Stubs for fused_ls_os and fused_3p ---
    code += """
fn impl_fused_ls_os(provider_ptr: Int,
                    ls_out: UnsafePointer[Float32, MutAnyOrigin],
                    os_out: UnsafePointer[Float32, MutAnyOrigin],
                    v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                    num_cols: Int) raises:
    pass  # Not used — fused_gradient covers all params

fn impl_fused_3p(provider_ptr: Int,
                 ls_out: UnsafePointer[Float32, MutAnyOrigin],
                 p1_out: UnsafePointer[Float32, MutAnyOrigin],
                 os_out: UnsafePointer[Float32, MutAnyOrigin],
                 v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                 num_cols: Int) raises:
    pass  # Not used — fused_gradient covers all params
"""

    # --- impl_extract_diagonal ---
    code += f"""
fn impl_extract_diagonal(provider_ptr: Int,
                         diag_ptr: UnsafePointer[Float32, MutAnyOrigin]) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
    ctx.enqueue_function[fused_extract_diagonal[DIM]](
        diag_ptr, prov[].x_ptr, prov[].params_gpu, n,
        grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    # --- impl_cross_matvec ---
    code += f"""
fn impl_cross_matvec(provider_ptr: Int,
                     out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                     x_test_ptr: UnsafePointer[Float32, MutAnyOrigin],
                     v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                     n_test: Int, num_cols: Int) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n_train = prov[].n
    var grid = ceildiv(n_test, BLOCK)
"""

    # NCOLS dispatch for cross matvec
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc) * 4
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_cross_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, x_test_ptr, prov[].x_ptr, v_ptr, prov[].params_gpu,\n"
        code += f"            n_test, n_train,\n"
        code += (
            f"            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )

    code += """    else:
        var col_start = 0
        while col_start < num_cols:
"""
    for nc in sorted(ncols_list, reverse=True):
        shmem = bs * (dim + nc) * 4
        code += f"""            if num_cols - col_start >= {nc}:
                var v_chunk = v_ptr.offset(col_start * n_train)
                var out_chunk = out_ptr.offset(col_start * n_test)
                ctx.enqueue_function[fused_cross_matvec_ncols[DIM, {nc}]](
                    out_chunk, x_test_ptr, prov[].x_ptr, v_chunk, prov[].params_gpu,
                    n_test, n_train,
                    grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})
                col_start += {nc}
                continue
"""
    code += """    ctx.synchronize()
"""

    # --- impl_extract_diagonal_test ---
    code += f"""
fn impl_extract_diagonal_test(provider_ptr: Int,
                              diag_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              x_test_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              n_test: Int) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var grid = ceildiv(n_test, BLOCK)
    ctx.enqueue_function[fused_extract_diagonal[DIM]](
        diag_ptr, x_test_ptr, prov[].params_gpu, n_test,
        grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    code += f"""
fn impl_fill_cross_covariance(provider_ptr: Int,
                              out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              x_test_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              n_test: Int) raises:
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n_train = prov[].n
    var grid = ceildiv(n_train, BLOCK)
    ctx.enqueue_function[fused_fill_cross_covariance[DIM]](
        out_ptr, x_test_ptr, prov[].x_ptr, prov[].params_gpu,
        n_test, n_train,
        grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    # --- impl_update_params ---
    code += f"""
fn impl_update_params(provider_ptr: Int,
                      params_host_ptr: UnsafePointer[Float32, MutAnyOrigin]) raises:
    var prov = _get_prov(provider_ptr)
    for i in range(NPARAMS):
        prov[].params_host[i] = params_host_ptr[i]
    var ctx = prov[].ctx
    var h = ctx.enqueue_create_host_buffer[DType.float32](NPARAMS)
    for i in range(NPARAMS):
        h.unsafe_ptr()[i] = params_host_ptr[i]
    ctx.enqueue_copy(dst_buf=prov[].params_gpu_owner[], src_buf=h)
    ctx.synchronize()
    _ = h
    if prov[].is_materialized and prov[].materialization_mode == 1:
        _do_materialize(prov)

fn impl_update_noise(provider_ptr: Int, noise: Float32):
    var prov = _get_prov(provider_ptr)
    if prov[].noise_mode == 0:
        prov[].noise = noise
    else:
        prov[].noise = Float32(0.0)

fn impl_get_noise(provider_ptr: Int) -> Float32:
    var prov = _get_prov(provider_ptr)
    if prov[].noise_mode == 1 or prov[].noise_mode == 2 or prov[].noise_mode == 3 or prov[].noise_mode == 4:
        # Vector-noise preconditioning uses get_noise_mode/get_noise_vector_ptr;
        # scalar callers still receive a finite floor for safety.
        return Float32(1e-6)
    return prov[].noise

fn impl_get_noise_mode(provider_ptr: Int) -> Int:
    var prov = _get_prov(provider_ptr)
    return prov[].noise_mode

fn impl_get_noise_vector_ptr(provider_ptr: Int) -> UnsafePointer[Float32, MutAnyOrigin]:
    var prov = _get_prov(provider_ptr)
    return prov[].noise_vec_ptr
"""

    # --- impl_get_diagonal_value ---
    # Compute from params (kernel-specific)
    diag_expr = _get_diagonal_value_expr(kernel)
    code += f"""
fn impl_get_diagonal_value(provider_ptr: Int) -> Float32:
    var prov = _get_prov(provider_ptr)
    var p = prov[].params_host
    return {diag_expr}

fn impl_kronecker_forward_matvec(provider_ptr: Int,
                                  out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                  v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                  B_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                  noise_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                  num_cols: Int, T: Int, outputscale: Float32) raises:
    \"\"\"Fused Kronecker forward matvec — NCOLS specialization (kernel computed once per j).\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
"""
    # NCOLS dispatch for Kronecker forward (same list as base kernel)
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_kronecker_forward_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,\n"
        code += f"            B_ptr, noise_ptr, n, T, num_cols, outputscale, 0,\n"
        code += f"            grid_dim=grid, block_dim=BLOCK)\n"
    code += """    else:
        for c in range(num_cols):
            ctx.enqueue_function[fused_kronecker_forward_matvec_ncols[DIM, 1]](
                out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,
                B_ptr, noise_ptr, n, T, num_cols, outputscale, c,
                grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()

fn impl_kronecker_gradient_matvec(provider_ptr: Int,
                                   out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                   v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                   B_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                   num_cols: Int, T: Int, outputscale: Float32) raises:
    \"\"\"Fused Kronecker gradient matvec — NCOLS specialization (kernel computed once per j).\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
"""
    # NCOLS dispatch for Kronecker gradient. Cap at NCOLS=6 to limit register pressure:
    # accumulator is NCOLS * MAX_T_GRAD(4) * NPARAMS floats, which grows fast.
    kron_grad_ncols = [nc for nc in ncols_list if nc <= 6]
    if not kron_grad_ncols:
        kron_grad_ncols = [1]
    for i, nc in enumerate(kron_grad_ncols):
        cond = "if" if i == 0 else "elif"
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_kronecker_gradient_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,\n"
        code += f"            B_ptr, n, T, num_cols, outputscale, 0,\n"
        code += f"            grid_dim=grid, block_dim=BLOCK)\n"
    code += """    else:
        for c in range(num_cols):
            ctx.enqueue_function[fused_kronecker_gradient_matvec_ncols[DIM, 1]](
                out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,
                B_ptr, n, T, num_cols, outputscale, c,
                grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    # --- impl_mixed_forward_matvec ---
    # shmem: bs * (DIM + NCOLS + MAX_CAT_VARS=8) * 4 bytes
    code += f"""
fn impl_mixed_forward_matvec(provider_ptr: Int,
                              out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              cat_indices: UnsafePointer[Int32, MutAnyOrigin],
                              corr_flat_ptr: UnsafePointer[Float32, MutAnyOrigin],
                              offsets_ptr: UnsafePointer[Int32, MutAnyOrigin],
                              levels_ptr: UnsafePointer[Int32, MutAnyOrigin],
                              num_cat_vars: Int,
                              num_cols: Int, noise: Float32) raises:
    \"\"\"Mixed forward matvec for arbitrary mixed-tree IR.\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    if prov[].is_materialized and prov[].materialization_mode == 2 and corr_flat_ptr == prov[].materialized_corr_ptr:
        _dense_matvec_naive(ctx, out_ptr, prov[].k_matrix_ptr, v_ptr, n, num_cols)
        var total = n * num_cols
        var grid_noise = ceildiv(total, BLOCK)
        ctx.enqueue_function[kernel_add_noise_vec](
            out_ptr, v_ptr, total, noise,
            grid_dim=grid_noise, block_dim=BLOCK)
        ctx.synchronize()
        return

    var grid = ceildiv(n, BLOCK)
"""
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc + 8) * 4  # +8 for MAX_CAT_VARS
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_mixed_forward_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,\n"
        code += f"            cat_indices, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,\n"
        code += f"            n, noise,\n"
        code += (
            f"            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )
    shmem_1 = bs * (dim + 1 + 8) * 4
    code += f"""    else:
        for c in range(num_cols):
            var v_col = v_ptr.offset(c * n)
            var out_col = out_ptr.offset(c * n)
            ctx.enqueue_function[fused_mixed_forward_matvec_ncols[DIM, 1]](
                out_col, v_col, prov[].x_ptr, prov[].params_gpu,
                cat_indices, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,
                n, noise,
                grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem_1})
    ctx.synchronize()
"""

    # --- impl_mixed_fused_gradient_matvec ---
    code += f"""
fn impl_mixed_fused_gradient_matvec(provider_ptr: Int,
                                     out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                     v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                     cat_indices: UnsafePointer[Int32, MutAnyOrigin],
                                     corr_flat_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                     offsets_ptr: UnsafePointer[Int32, MutAnyOrigin],
                                     levels_ptr: UnsafePointer[Int32, MutAnyOrigin],
                                     num_cat_vars: Int,
                                     num_cols: Int) raises:
    \"\"\"Mixed fused all-gradients matvec for arbitrary mixed-tree IR.\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
"""
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc + 8) * 4
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_mixed_all_gradients_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,\n"
        code += f"            cat_indices, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,\n"
        code += f"            n,\n"
        code += (
            f"            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )
    shmem_1 = bs * (dim + 1 + 8) * 4
    code += f"""    else:
        ctx.enqueue_function[fused_mixed_all_gradients_matvec_ncols[DIM, 1]](
            out_ptr, v_ptr, prov[].x_ptr, prov[].params_gpu,
            cat_indices, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,
            n,
            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem_1})
    ctx.synchronize()
"""

    # --- impl_mixed_cross_matvec ---
    code += f"""
fn impl_mixed_cross_matvec(provider_ptr: Int,
                            out_ptr: UnsafePointer[Float32, MutAnyOrigin],
                            x_test_ptr: UnsafePointer[Float32, MutAnyOrigin],
                            v_ptr: UnsafePointer[Float32, MutAnyOrigin],
                            cat_test: UnsafePointer[Int32, MutAnyOrigin],
                            cat_train: UnsafePointer[Int32, MutAnyOrigin],
                            corr_flat_ptr: UnsafePointer[Float32, MutAnyOrigin],
                            offsets_ptr: UnsafePointer[Int32, MutAnyOrigin],
                            levels_ptr: UnsafePointer[Int32, MutAnyOrigin],
                            num_cat_vars: Int,
                            n_test: Int, num_cols: Int) raises:
    \"\"\"Mixed cross-covariance matvec for arbitrary mixed-tree IR.\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n_train = prov[].n
    var grid = ceildiv(n_test, BLOCK)
"""
    for i, nc in enumerate(ncols_list):
        cond = "if" if i == 0 else "elif"
        shmem = bs * (dim + nc + 8) * 4
        code += f"    {cond} num_cols == {nc}:\n"
        code += f"        ctx.enqueue_function[fused_mixed_cross_matvec_ncols[DIM, {nc}]](\n"
        code += f"            out_ptr, x_test_ptr, prov[].x_ptr, v_ptr, prov[].params_gpu,\n"
        code += f"            cat_test, cat_train, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,\n"
        code += f"            n_test, n_train,\n"
        code += (
            f"            grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem})\n"
        )
    shmem_1 = bs * (dim + 1 + 8) * 4
    code += f"""    else:
        for c in range(num_cols):
            var v_col = v_ptr.offset(c * n_train)
            var out_col = out_ptr.offset(c * n_test)
            ctx.enqueue_function[fused_mixed_cross_matvec_ncols[DIM, 1]](
                out_col, x_test_ptr, prov[].x_ptr, v_col, prov[].params_gpu,
                cat_test, cat_train, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,
                n_test, n_train,
                grid_dim=grid, block_dim=BLOCK, shared_mem_bytes={shmem_1})
    ctx.synchronize()
"""

    # --- impl_mixed_extract_diagonal ---
    code += f"""
fn impl_mixed_extract_diagonal(provider_ptr: Int,
                                diag_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                cat_indices: UnsafePointer[Int32, MutAnyOrigin],
                                corr_flat_ptr: UnsafePointer[Float32, MutAnyOrigin],
                                offsets_ptr: UnsafePointer[Int32, MutAnyOrigin],
                                levels_ptr: UnsafePointer[Int32, MutAnyOrigin],
                                num_cat_vars: Int) raises:
    \"\"\"Mixed diagonal extraction for arbitrary mixed-tree IR.\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    var grid = ceildiv(n, BLOCK)
    ctx.enqueue_function[fused_mixed_extract_diagonal[DIM]](
        diag_ptr, prov[].x_ptr, prov[].params_gpu,
        cat_indices, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,
        n,
        grid_dim=grid, block_dim=BLOCK)
    ctx.synchronize()
"""

    code += f"""
fn impl_mixed_materialize(provider_ptr: Int,
                           cat_indices: UnsafePointer[Int32, MutAnyOrigin],
                           corr_flat_ptr: UnsafePointer[Float32, MutAnyOrigin],
                           offsets_ptr: UnsafePointer[Int32, MutAnyOrigin],
                           levels_ptr: UnsafePointer[Int32, MutAnyOrigin],
                           num_cat_vars: Int) raises:
    \"\"\"Materialize the full arbitrary mixed kernel matrix on GPU.\"\"\"
    var prov = _get_prov(provider_ptr)
    var ctx = prov[].ctx
    var n = prov[].n
    if not prov[].is_materialized:
        var K_buf = ctx.enqueue_create_buffer[DType.float32](n * n)
        prov[].k_matrix_ptr = K_buf.unsafe_ptr()
        var K_heap = alloc[DeviceBuffer[DType.float32]](1)
        K_heap.init_pointee_move(K_buf^)
        prov[].k_matrix_owner = K_heap
        prov[].is_materialized = True
    prov[].materialization_mode = 2
    prov[].materialized_corr_ptr = corr_flat_ptr
    alias TILE = 16
    var grid_x = ceildiv(n, TILE)
    var grid_y = ceildiv(n, TILE)
    ctx.enqueue_function[fused_mixed_fill_kernel_matrix[DIM]](
        prov[].k_matrix_ptr, prov[].x_ptr, prov[].params_gpu,
        cat_indices, corr_flat_ptr, offsets_ptr, levels_ptr, num_cat_vars,
        n,
        grid_dim=(grid_x, grid_y), block_dim=(TILE, TILE))
    ctx.synchronize()
"""

    return code


def _get_diagonal_value_expr(kernel: IRKernel) -> str:
    """Get the diagonal value expression for K(x, x).

    For stationary kernels, K(x,x) = outputscale (dist_sq=0 → exp(0)=1).
    For non-stationary kernels, we need to evaluate the forward expression
    with dist_sq=0 and dot_prod=||x||^2.

    For simplicity, return the outputscale param (p[last]) for stationary,
    and Float32(1.0) as a safe default for non-stationary.
    """
    # The last param is typically outputscale for standard kernels
    # For composites this is approximate but safe (preconditioner uses it as hint)
    if kernel.num_params > 0:
        return f"p[{kernel.num_params - 1}]"
    return "Float32(1.0)"


def _emit_helpers_and_bindings(num_params: int, module_name: str, is_ard: bool) -> str:
    """Emit fn-ptr type aliases, init_provider, materialize, and PyInit."""
    return f'''
# {"=" * 77}
# Fn ptr type aliases and conversion helpers
# {"=" * 77}

alias FwdFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int) raises -> None
alias GradFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int, Int, Bool) raises -> None
alias FusedFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int) raises -> None
alias LsOsFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int) raises -> None
alias ThreePFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int) raises -> None
alias DiagFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin]) raises -> None
alias UpdPFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin]) raises -> None
alias UpdNFn = fn(Int, Float32) -> None
alias GetFFn = fn(Int) -> Float32
alias GetIntFn = fn(Int) -> Int
alias GetPtrFn = fn(Int) -> UnsafePointer[Float32, MutAnyOrigin]
alias CrossFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int, Int) raises -> None
alias DiagTestFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int) raises -> None
alias FillCrossFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int) raises -> None
alias KronFwdFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int, Int, Float32) raises -> None
alias KronGradFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], Int, Int, Float32) raises -> None
alias MixedFwdFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], Int, Int, Float32) raises -> None
alias MixedFusedGradFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], Int, Int) raises -> None
alias MixedCrossFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], Int, Int, Int) raises -> None
alias MixedDiagFn = fn(Int, UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], Int) raises -> None
alias MixedMatFn = fn(Int, UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Float32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], UnsafePointer[Int32, MutAnyOrigin], Int) raises -> None

# {"=" * 77}
# Python bindings
# {"=" * 77}

fn init_provider_python(py_self: PythonObject, args: PythonObject) raises -> PythonObject:
    """Create provider and return fn ptr dict.

    args[0]: X numpy array [n, dim] float32
    args[1]: initial_params numpy array [NPARAMS] float32
    args[2]: initial_noise (float)
    args[3]: optional observation noise vector [n] float32
    args[4]: optional vector noise mode, 1=fixed vector, 2=learned vector, 3=learned grouped, 4=learned linear input-dependent
    args[5]: optional int32 noise group ids [n]
    args[6]: optional number of noise groups
    """
    var np = Python.import_module("numpy")
    var X_np = args[0].astype(np.float32)
    var params_np = args[1].astype(np.float32).flatten()
    var init_noise = Float32(args[2].__float__())
    var has_noise_vector = len(args) > 3
    var vector_noise_mode = 1
    if len(args) > 4:
        vector_noise_mode = Int(args[4].__int__())
        if vector_noise_mode != 1 and vector_noise_mode != 2 and vector_noise_mode != 3 and vector_noise_mode != 4:
            raise Error("vector noise mode must be 1=fixed_vector, 2=learned_vector, 3=learned_grouped, or 4=learned_input_dependent")
    var has_noise_groups = len(args) > 5
    var num_noise_groups = 0
    if has_noise_groups:
        num_noise_groups = Int(args[6].__int__())

    var n = Int(X_np.shape[0])
    var dim = Int(X_np.shape[1])

    # Copy X to GPU
    var ctx = DeviceContext()
    var x_host = ctx.enqueue_create_host_buffer[DType.float32](n * dim)
    var X_flat = X_np.flatten()
    for i in range(n * dim):
        x_host.unsafe_ptr()[i] = Float32(X_flat[i].__float__())
    var x_device = ctx.enqueue_create_buffer[DType.float32](n * dim)
    ctx.enqueue_copy(x_device, x_host)
    ctx.synchronize()

    # Allocate params on host (persistent)
    var params_host = alloc[Float32]({num_params})
    for i in range({num_params}):
        params_host[i] = Float32(params_np[i].__float__())

    # Create GPU buffer for params
    var params_host_buf = ctx.enqueue_create_host_buffer[DType.float32]({num_params})
    ctx.synchronize()
    for i in range({num_params}):
        params_host_buf.unsafe_ptr()[i] = params_host[i]
    var params_gpu_buf = ctx.enqueue_create_buffer[DType.float32]({num_params})
    ctx.enqueue_copy(params_gpu_buf, params_host_buf)
    ctx.synchronize()
    var params_gpu_ptr = params_gpu_buf.unsafe_ptr()

    # Heap-allocate buffers and store the owners on the provider so the raw
    # x_ptr / params_gpu pointers stay valid across later GPU allocations.
    var gpu_buf_heap = alloc[DeviceBuffer[DType.float32]](1)
    gpu_buf_heap.init_pointee_move(params_gpu_buf^)
    var x_device_ptr = x_device.unsafe_ptr()
    var x_dev_heap = alloc[DeviceBuffer[DType.float32]](1)
    x_dev_heap.init_pointee_move(x_device^)

    var noise_vec_ptr = UnsafePointer[Float32, MutAnyOrigin]()
    var noise_vec_heap = UnsafePointer[DeviceBuffer[DType.float32], MutAnyOrigin]()
    var noise_group_ptr = UnsafePointer[Int32, MutAnyOrigin]()
    var noise_group_heap = UnsafePointer[DeviceBuffer[DType.int32], MutAnyOrigin]()
    if has_noise_vector:
        var noise_np = args[3].astype(np.float32).flatten()
        if Int(noise_np.shape[0]) != n:
            raise Error("observation_noise must have shape (n,)")
        var noise_host = ctx.enqueue_create_host_buffer[DType.float32](n)
        for i in range(n):
            noise_host.unsafe_ptr()[i] = Float32(noise_np[i].__float__())
        var noise_device = ctx.enqueue_create_buffer[DType.float32](n)
        ctx.enqueue_copy(noise_device, noise_host)
        ctx.synchronize()
        noise_vec_ptr = noise_device.unsafe_ptr()
        noise_vec_heap = alloc[DeviceBuffer[DType.float32]](1)
        noise_vec_heap.init_pointee_move(noise_device^)
        _ = noise_host
    if has_noise_groups:
        var group_np = args[5].astype(np.int32).flatten()
        if Int(group_np.shape[0]) != n:
            raise Error("noise_group_train must have shape (n,)")
        var group_host = ctx.enqueue_create_host_buffer[DType.int32](n)
        for i in range(n):
            group_host.unsafe_ptr()[i] = Int32(Int(group_np[i]))
        var group_device = ctx.enqueue_create_buffer[DType.int32](n)
        ctx.enqueue_copy(group_device, group_host)
        ctx.synchronize()
        noise_group_ptr = group_device.unsafe_ptr()
        noise_group_heap = alloc[DeviceBuffer[DType.int32]](1)
        noise_group_heap.init_pointee_move(group_device^)
        _ = group_host

    # Heap-allocate provider
    var prov_heap = alloc[JITProvider](1)
    prov_heap.init_pointee_move(JITProvider(
        ctx,
        params_host,
        gpu_buf_heap,
        params_gpu_ptr,
        init_noise,
        n,
        dim,
        x_dev_heap,
        x_device_ptr,
    ))
    if has_noise_vector:
        prov_heap[].noise_mode = vector_noise_mode
        prov_heap[].noise = Float32(0.0)
        prov_heap[].noise_vec_owner = noise_vec_heap
        prov_heap[].noise_vec_ptr = noise_vec_ptr
        if has_noise_groups:
            prov_heap[].noise_group_owner = noise_group_heap
            prov_heap[].noise_group_ptr = noise_group_ptr
            prov_heap[].num_noise_groups = num_noise_groups
    var prov_addr = Int(prov_heap)

    # Build fn ptr dict
    var py = Python()
    var result = py.dict()
    result["provider_ptr"] = prov_addr
    result["n"] = n
    result["dim"] = dim
    result["num_gradient_params"] = {num_params}
    result["supports_fused_gradient"] = True
    result["supports_fused_ls_os"] = False
    result["supports_fused_3param"] = False
    result["x_ptr"] = Int(x_device_ptr)
    if has_noise_vector and vector_noise_mode == 4:
        result["x_host"] = X_np
    result["is_ard"] = {"True" if is_ard else "False"}
    result["materialization_mode"] = 0
    if has_noise_vector and vector_noise_mode == 4:
        result["noise_mode"] = "learned_input_dependent"
    elif has_noise_vector and vector_noise_mode == 3:
        result["noise_mode"] = "learned_grouped"
    elif has_noise_vector and vector_noise_mode == 2:
        result["noise_mode"] = "learned_vector"
    else:
        result["noise_mode"] = "fixed_vector" if has_noise_vector else "scalar"
    result["has_observation_noise_vector"] = has_noise_vector
    result["noise_group_ptr"] = Int(noise_group_ptr) if has_noise_groups else 0
    result["num_noise_groups"] = num_noise_groups

    # Function pointer addresses (fn → Int via bitcast)
    var s1 = alloc[FwdFn](1); s1[] = impl_forward_matvec; result["forward_matvec"] = s1.bitcast[Int]()[]; s1.free()
    var s2 = alloc[GradFn](1); s2[] = impl_gradient_matvec; result["gradient_matvec"] = s2.bitcast[Int]()[]; s2.free()
    var s3 = alloc[FusedFn](1); s3[] = impl_fused_gradient_matvec; result["fused_gradient_matvec"] = s3.bitcast[Int]()[]; s3.free()
    var s4 = alloc[LsOsFn](1); s4[] = impl_fused_ls_os; result["fused_ls_os_gradient_matvec"] = s4.bitcast[Int]()[]; s4.free()
    var s5 = alloc[ThreePFn](1); s5[] = impl_fused_3p; result["fused_3param_gradient_matvec"] = s5.bitcast[Int]()[]; s5.free()
    var s6 = alloc[DiagFn](1); s6[] = impl_extract_diagonal; result["extract_diagonal"] = s6.bitcast[Int]()[]; s6.free()
    var s7 = alloc[UpdPFn](1); s7[] = impl_update_params; result["update_params"] = s7.bitcast[Int]()[]; s7.free()
    var s8 = alloc[UpdNFn](1); s8[] = impl_update_noise; result["update_noise"] = s8.bitcast[Int]()[]; s8.free()
    var s9 = alloc[GetFFn](1); s9[] = impl_get_noise; result["get_noise"] = s9.bitcast[Int]()[]; s9.free()
    var s9m = alloc[GetIntFn](1); s9m[] = impl_get_noise_mode; result["get_noise_mode"] = s9m.bitcast[Int]()[]; s9m.free()
    var s9v = alloc[GetPtrFn](1); s9v[] = impl_get_noise_vector_ptr; result["get_noise_vector_ptr"] = s9v.bitcast[Int]()[]; s9v.free()
    var s10 = alloc[GetFFn](1); s10[] = impl_get_diagonal_value; result["get_diagonal_value"] = s10.bitcast[Int]()[]; s10.free()
    var s11 = alloc[CrossFn](1); s11[] = impl_cross_matvec; result["cross_matvec"] = s11.bitcast[Int]()[]; s11.free()
    var s12 = alloc[DiagTestFn](1); s12[] = impl_extract_diagonal_test; result["extract_diagonal_test"] = s12.bitcast[Int]()[]; s12.free()
    var s13 = alloc[FillCrossFn](1); s13[] = impl_fill_cross_covariance; result["fill_cross_covariance"] = s13.bitcast[Int]()[]; s13.free()
    var s14 = alloc[KronFwdFn](1); s14[] = impl_kronecker_forward_matvec; result["kronecker_forward_matvec"] = s14.bitcast[Int]()[]; s14.free()
    var s15 = alloc[KronGradFn](1); s15[] = impl_kronecker_gradient_matvec; result["kronecker_gradient_matvec"] = s15.bitcast[Int]()[]; s15.free()
    var s16 = alloc[MixedFwdFn](1); s16[] = impl_mixed_forward_matvec; result["mixed_forward_matvec"] = s16.bitcast[Int]()[]; s16.free()
    var s17 = alloc[MixedFusedGradFn](1); s17[] = impl_mixed_fused_gradient_matvec; result["mixed_fused_gradient_matvec"] = s17.bitcast[Int]()[]; s17.free()
    var s18 = alloc[MixedCrossFn](1); s18[] = impl_mixed_cross_matvec; result["mixed_cross_matvec"] = s18.bitcast[Int]()[]; s18.free()
    var s19 = alloc[MixedDiagFn](1); s19[] = impl_mixed_extract_diagonal; result["mixed_extract_diagonal"] = s19.bitcast[Int]()[]; s19.free()
    var s20 = alloc[MixedMatFn](1); s20[] = impl_mixed_materialize; result["mixed_materialize"] = s20.bitcast[Int]()[]; s20.free()

    _ = x_host
    return result

fn materialize_python(py_self: PythonObject, args: PythonObject) raises -> PythonObject:
    """Materialize the kernel matrix K for cuBLAS-accelerated forward matvec.

    args[0]: provider_info dict (from init_provider)
    """
    var info = args[0]
    var provider_ptr = Int(info["provider_ptr"].__int__())
    var prov = _get_prov(provider_ptr)
    _do_materialize(prov)
    info["materialization_mode"] = 1
    return PythonObject(True)

fn destroy_provider_python(py_self: PythonObject, args: PythonObject) raises -> PythonObject:
    """Destroy a provider created by init_provider()."""
    var info = args[0]
    var provider_ptr = Int(info["provider_ptr"].__int__())
    if provider_ptr != 0:
        var prov = _get_prov(provider_ptr)
        var ctx = prov[].ctx
        ctx.synchronize()
        _destroy_provider(prov)
        ctx.synchronize()
        info["provider_ptr"] = 0
        info["x_ptr"] = 0
        info["materialization_mode"] = 0
    return PythonObject(True)

@export
fn PyInit_{module_name}() -> PythonObject:
    try:
        var m = PythonModuleBuilder("{module_name}")
        m.def_py_function[init_provider_python]("init_provider",
            docstring="Create provider and return fn ptr addresses")
        m.def_py_function[materialize_python]("materialize",
            docstring="Materialize K matrix for cuBLAS-accelerated forward matvec")
        m.def_py_function[destroy_provider_python]("destroy_provider",
            docstring="Destroy a provider created by init_provider")
        return m.finalize()
    except e:
        return abort[PythonObject]("Failed to init {module_name}: " + String(e))
'''
